<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Testing" Version="2026.8.22.9588" />
		<PackageReference Include="Krosoft.Extensions.WebApi" Version="2026.8.23.9620" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\samples\Krosoft.Extensions.Samples.Library\Krosoft.Extensions.Samples.Library.csproj" />
		<ProjectReference Include="..\..\src\Krosoft.Extensions.Validations\Krosoft.Extensions.Validations.csproj" />
	</ItemGroup>
</Project>